# Generated by Django 3.2 on 2021-04-13 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('pages', models.IntegerField(verbose_name='Quantidade de páginas')),
                ('date_release', models.DateTimeField(verbose_name='Data de lançamento')),
            ],
            bases=('core.base',),
        ),
    ]
