# Generated by Django 3.2 on 2021-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_release',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de lançamento'),
        ),
    ]
