# Generated by Django 3.2 on 2021-04-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_books_date_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date_release',
        ),
    ]
