# Generated by Django 3.2 on 2021-04-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_books_date_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_release',
            field=models.CharField(default='', max_length=15, verbose_name='Data de lançamento'),
        ),
    ]
